spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: studentManagement
  datasource:
    url: jdbc:mysql://localhost:3306/student_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
doma:
  dialect: mysql
