package com.example.studentmangerment.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.seasar.doma.*;

/**
 * Persistent entity mapped to the {@code student} table (core student identity and code).
 */
@Entity(immutable = true)
@Table(name = "student")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Student {
    /** Primary key; generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "student_id")
    private Integer id;
    /** Display name of the student. */
    @Column(name = "student_name")
    private String name;
    /** Business identifier (e.g. {@code STU001}), unique in the application domain. */
    @Column(name = "student_code")
    private String code;

}
