package com.example.studentmangerment.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.seasar.doma.*;

import java.util.Date;

/**
 * Persistent entity mapped to the {@code student_info} table (address, scores, birthday for a student).
 */
@Entity(immutable = true)
@Table(name = "student_info")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StudentInfo {
    /** Primary key of the info row; generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "info_id")
    private Integer id;
    /** Foreign key referencing {@link Student#getId()}. */
    @Column(name = "student_id")
    private int studentId;
    /** Postal or contact address. */
    private String address;
    /** Academic average score (application-specific scale). */
    @Column(name = "average_score")
    private double averageScore;
    /** Date of birth. */
    @Column(name = "date_of_birth")
    private Date birthday;
}
