package com.example.studentmangerment.entity;

import lombok.*;
import org.seasar.doma.*;

/**
 * Persistent entity mapped to the {@code user} table for authentication and authorization.
 */
@Entity(immutable = true)
@Table(name = "user")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** Primary key; generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Integer id;
    /** Unique login name (validated as email-shaped in API requests). */
    @Column(name = "user_name")
    private String username;
    /** BCrypt-hashed password. */
    @Column(name = "password")
    private String password;
    /** Application role: {@code USER} or {@code ADMIN} (stored without {@code ROLE_} prefix). */
    private String role;
}
